---
voxceleb_large_1s:
  signal:
    duration: 1
  train:
    batch_size: 128
    data_path: '/data/public/rw/voxceleb_norm'
    meta_path: '/data/public/rw/voxceleb/speaker_list.csv'
    num_gpu: 4
    lr: 0.0001
  eval:
    data_path: '/data/public/rw/voxceleb_norm'
  embed:
    batch_size: 512
    audio_meta_class: 'CommonVoiceMeta'
    data_path: '/data/public/rw/cv-valid-train/trimmed'
    meta_path: '/data/public/rw/cv_corpus_v1/cv-valid-train.csv'
    meta_field_viz: 'gender'
---
voxceleb_large_4s:
  signal:
    win_length: 512
    hop_length: 128
    duration: 4
  model:
    hidden_units: 512
  train:
    batch_size: 128
    data_path: '/data/public/rw/voxceleb_norm'
    meta_path: '/data/public/rw/voxceleb/speaker_list.csv'
    num_gpu: 4
    lr: 0.0001
  eval:
    data_path: '/data/public/rw/voxceleb_norm'
  embed:
    batch_size: 1024
    audio_meta_class: 'TestAudioMeta'
    data_path: '/data/public/rw/IU/melon_radio_season2_split'
#    meta_path: '/data/public/rw/cv_corpus_v1/cv-valid-train.csv'
#    meta_field_viz: 'gender'